component: website
name: dj-website
app: app-dj-website
stage: prod

inputs:
  src:
    src: ./build
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: dj-website
  protocol: https
