import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  noteSidebar: [
    {
      type: 'autogenerated',
      dirName: 'note',
    },
  ],
  codeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'code',
    },
  ],
};

export default sidebars;
