import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  frontendBase: [
    {
      type: 'autogenerated',
      dirName: 'frontend-base',
    },
  ],
  wheelSource: [
    {
      type: 'autogenerated',
      dirName: 'wheel-source',
    },
  ],
};

export default sidebars;
