name: Algolia Crawl Indices

on:
  workflow_dispatch:

jobs:
  steps:
    name: Crawl
    uses: darrenjennings/algolia-docsearch-action@master
    with:
      algolia_application_id: ${{ secrets.ALGOLIA_APPID }}
      algolia_api_key: ${{ secrets.ALGOLIA_APIKEY }}
      file: 'algolia.config.json'
